#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "$HOME/.dotfiles/prezto/init.zsh" ]]; then
  source "$HOME/.dotfiles/prezto/init.zsh"
fi

# Customize to your needs...

# Source .localrc if available
if [[ -s "$HOME/.localrc" ]]; then
  source "$HOME/.localrc"
fi

# Source alias and functions
source $HOME/.dotfiles/system/function
source $HOME/.dotfiles/system/alias

# Load z
. $HOME/.dotfiles/modules/z/z.sh

# Show only current folder path
prompt_dir() {
  prompt_segment blue $PRIMARY_FG " `basename ${PWD/#$HOME/'~'}` "
}
