#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "$HOME/.dotfiles/prezto/init.zsh" ]]; then
  source "$HOME/.dotfiles/prezto/init.zsh"
fi

# Customize to your needs...

# Source .localrc if available
if [[ -s "$HOME/.localrc" ]]; then
  source "$HOME/.localrc"
fi

# Source alias and functions
source $HOME/.dotfiles/system/function
source $HOME/.dotfiles/system/alias

# Load nvm
export NVM_LAZY_LOAD=true
source $HOME/.dotfiles/modules/nvm/zsh-nvm.plugin.zsh

# Load z
. $HOME/.dotfiles/modules/z/z.sh
