geporting: "off"
reporting: "off"
startuppopupversion: 1

gui:
  showFileTree: false

keybinding:
  commits:
    moveDownCommit: <c-b>
    moveUpCommit: <c-g>

customCommands:
  - key: <c-r>
    command: "git remote prune {{.SelectedRemote.Name}}"
    context: remoteBranches
    description: Prune deleted branches
    loadingText: Pruning remote...
