#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "$DOTFILES_DIR/prezto/init.zsh" ]]; then
  source "$DOTFILES_DIR/prezto/init.zsh"
fi

# Customize to your needs...

# Source .localrc if exists
if [[ -s $HOME/.localrc ]]; then
  source $HOME/.localrc
fi

#load z
. $DOTFILES_DIR/prezto/modules/z/z.sh
