"
" vim config
" inspired by xero's dotfiles [https://github.com/xero/dotfiles]
"

let configs = [
\  "basic",
\  "plugins",
\  "plugin-settings",
\  "coc",
\]

for file in configs
  let x = expand("~/.vim/".file.".vim")
  if filereadable(x)
    execute 'source' x
  endif
endfor
