"
" __   _____ __  __
" \ \ / /_ _|  \/  |
"  \ V / | || |\/| |
"   \_/ |___|_|  |_|
"

execute "source ~/.vim/basic.vim"

if !empty(glob('~/.vim/autoload/plug.vim')) && !has('nvim')
  execute "source ~/.vim/plugins.vim"
  execute "source ~/.vim/plugin-settings.vim"
endif
