" General Vim settings
" # Vundle
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" git commands
Plugin 'tpope/vim-fugitive'
" git change indicator
Plugin 'airblade/vim-gitgutter'
" file tree pane
Plugin 'scrooloose/nerdtree'
" powerful commenter
Plugin 'scrooloose/nerdcommenter'
" syntax checker (checker install required)
Plugin 'w0rp/ale'
" replace surrounding quotes/parenthesis 
Plugin 'tpope/vim-surround'
" auto insert quotes/parenthesis
Plugin 'jiangmiao/auto-pairs'
" better terminal integration
Plugin 'wincent/terminus'
" statusbar
Plugin 'itchyny/lightline.vim'
" multiple cursor selection
Plugin 'terryma/vim-multiple-cursors'
" color previewer
Plugin 'gorodinskiy/vim-coloresque'
" indent lines
Plugin 'Yggdroot/indentLine'
" improved js indent and syntax highlighting
Plugin 'pangloss/vim-javascript'
" html5 omnicomplete and syntax
Plugin 'othree/html5.vim'
" emmet
Plugin 'mattn/emmet-vim'
" vue syntax highlighting
Plugin 'posva/vim-vue'
" fuzzy file finder
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plugin 'junegunn/fzf.vim'
" autocompletion
if has('nvim')
  Plugin 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plugin 'Shougo/deoplete.nvim'
  Plugin 'roxma/nvim-yarp'
  Plugin 'roxma/vim-hug-neovim-rpc'
endif

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" https://dougblack.io/words/a-good-vimrc.html
" # Color
	colorscheme molokai
	syntax enable

" # Spaces & Tabs
	set autoindent
	set tabstop=2
	set softtabstop=2
	set expandtab

" # UI Config
	set number
	set cursorline
	set relativenumber 
	set wildmenu
	set lazyredraw
	set showmatch
  set hlsearch
  set updatetime=100
	filetype indent on

" # Leader Shortcuts
	let mapleader=" "
	inoremap jk <esc>

" # Backups
	set dir=/tmp/

" Emmet settings
" # expand with tab
imap <expr> <tab> emmet#expandAbbrIntelligent("\<tab>")

" NERDTree settings
" # right arrow to open node
let NERDTreeMapActivateNode = '<right>'
" # display hidden files
let NERDTreeShowHidden = 1
" # toggle display of tree with <Leader> + n
nmap <leader>n :NERDTreeToggle<CR>
" # locate the focused file in tree with <Leader> + j
nmap <leader>j :NERDTreeFind<CR>
" # ignore these files in tree
let NERDTreeIgnore=['\.DS_Store', '\~$', '\.swp']

" fzf settings
" # set fzf trigger key
noremap <leader>t :FZF<CR>

" lightline settings
" # show statusline
set laststatus=2
" # hide default statusline
set noshowmode

" vim-multiple-cursors settings
" # remap select all instance
let g:multi_cursor_select_all_key = '<leader>d'

" deoplete settings
" # enable autocomplete on startup
let g:deoplete#enable_at_startup = 1
